spring:
  config:
    activate:
      on-profile:
        - sandbox
        - dev
        - stg
        - prod
  application:
    name: Game Server
  data:
    redis:
      port: ${CONF_REDIS_PORT}
      host: ${CONF_REDIS_HOST}
      password: ${CONF_REDIS_PASSWORD}
      database: 2
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      jdbc-url: jdbc:postgresql://${CONF_POSTGRES_HOST}:${CONF_POSTGRES_PORT}/${CONF_POSTGRES_DB}
      username: ${CONF_POSTGRES_USERNAME}
      password: ${CONF_POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  grpc:
    server:
      port: ${CONF_SERVER_PORT}
